# Generated by Django 4.1.1 on 2022-10-06 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('striked', models.BooleanField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
