# Generated by Django 4.1.1 on 2022-10-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='striked',
            field=models.IntegerField(),
        ),
    ]
